= Челлендж 'React step-by-step'

== FAQ

=== Зачем?

Для того чтобы написать своими руками приложения на Реакте с нуля.

=== Для кого?

Для всех, кто знает базовые функции Реакта, но не понимает как они работают в рамках целого приложения и взаимодействуют друг с другом

=== В чем суть процесса обучения?

Как такового обучения не будет — будет набор шагов, которые нужно выполнить, чтобы добраться к финишу. По пути нужно будет много гуглить и советоваться с более опытными коллегами. Хотя после каждого шага будет предоставлен скриншот, видео, снапшот кода для того, чтобы понимать что нужно сделать и свериться на правильном ли ты пути

== Описание проекта

Проект состоит из двух частей:

. Плана разработки приложения с нуля
. Вспомогательной части — сервера, который написан специально для целей обучения.

Отдельно хотелось бы остановиться на плюсах серверного приложения:

. для работы сервера не требуется подключения к базам данных;
. для целей обучения можно использовать jar файл, который легко запускается из CMD. После этого можно использовать АПИ сервера;
. сервер при первом запуске уже содержит внутри тестовые данные
. легко сбросить изменения, внесенные на сервер — достаточно просто его перезапустить

