= Челлендж 'React step-by-step'

== FAQ

=== Зачем?

Для того чтобы написать своими руками приложения на Реакте с нуля.

=== Для кого?

. Для всех, кто знает базовые функции Реакта, но не понимает как они работают в рамках целого приложения и взаимодействуют друг с другом
. Для тех, у кого нет идей с чего начать свое приложение
. Для тех, кто хочет попробовать на практике отладить взаимодействие клиента и сервера

=== В чем суть процесса обучения?

Как такового обучения не будет — будет набор шагов, которые нужно выполнить, чтобы добраться к финишу.
По пути нужно будет много гуглить и советоваться с более опытными коллегами.
Хотя после каждого шага будет предоставлен скриншот, видео или код приложения для того, чтобы свериться

== Описание проекта

Проект состоит из двух частей:

. План разработки приложения с нуля https://github.com/eugene-kuntsevich/react-step-by-step/tree/master/react-project-steps[здесь]
. Вспомогательной части — сервера, который написан специально для целей обучения https://github.com/eugene-kuntsevich/react-step-by-step/tree/master/test-server[здесь]

*Важный момент* — все шаги плана по написанию приложения на реакте согласованы с серверной реализацией

Отдельно хотелось бы остановиться на плюсах серверного приложения:

. для работы сервера не требуется подключения к базам данных;
. для целей обучения можно использовать jar файл, который легко запускается из CMD.
После этого можно использовать АПИ сервера; ```TODO добавить ссылку на jar```
. сервер при первом запуске уже содержит внутри тестовые данные
. легко сбросить изменения, внесенные на сервер — достаточно просто его перезапустить
. все запросы добавлены могут быть протестированы с помощью Swagger

Минусы:

. здесь не получится освоить CSS стили и UI/UX

